# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    container_name: sweet_pascal
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      -postgres_data:/var/lib/postgresql/data
    networks:
      - app-network 

  app:
    build: .
    container_name: go_app
    depends_on:
      - db
    ports:
      -"8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: disable
    networks:
      - app-network
    volumes:
      - .:/app
    command: ["./scripts/wait-for-postgres.sh", "db:5432", "--", "go", "run", "main.go"]

volumes:
  postgres_data

networks:
  app-network:
    
